name: eds_test
description: A mini demo app for ESD

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  async: ^2.8.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  get_it: ^7.2.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  stacked: ^2.2.7+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
